# Site settings
title: "ê¶Œë„í›ˆì˜ ê¸°ìˆ ë¸”ë¡œê·¸"
bye_message: "ê°ì‚¬í•©ë‹ˆë‹¤"
baseurl: "/blog/"
url: "https://dd4f-dohun.github.io"
disqus: 

# Header settings
nick: "dd4f-dohun"
mail:
    domain: "protonmail"
    ext: "ch"
source_code:
    server: "github.com"
    nick: "dd4f-dohun"
blog:
    server: "wordpress.com"
    nick: "dd4f-dohun"
fingerprint_key: "ë°©ì§€ì›ğŸ‘†"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
